# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Market.Comparison.Auth

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ "main" ]

env:
  webProject: '**/Market.Comparison.Auth.csproj'
  webProjectPath: '' # will be set in a later step
  testProjects: '**/*[Tt]ests/*.csproj'
  buildConfiguration: ${{ github.ref == 'refs/heads/main' && 'Release' || 'Debug' }}

jobs:
  build-market-comparison-auth:
    name: Build Market.Comparison.Auth
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Disable shallow fetch to get the full history of the repository

    - name: Setup Git Version
      uses: GitTools/actions/gitversion/setup@v0.10.2
      with:
        versionSpec: '5.x'

    - name: Execute Git Version
      uses: GitTools/actions/gitversion/execute@v0.10.2
      with:
        updateAssemblyInfo: false
        useConfigFile: true
        configFilePath: '.github/GitVersion.yml'

    - name: Find web project's' physical path
      run: |
        $path = Get-ChildItem -Path . -Filter Market.Comparison.Auth.csproj -Recurse | Select-Object -First 1 -ExpandProperty FullName
        Write-Host "webProjectPath value -> $path"
        echo "webProjectPath=$path" >> $GITHUB_ENV
      shell: pwsh

    - name: Print variable
      run: echo $webProjectPath

    - name: Use .NET 8 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x

    - name: Restore web project
      run: dotnet restore ${{ env.webProject }} --verbosity Minimal

    - name: Restore test project
      run: dotnet restore ${{ env.testProjects }} --verbosity Minimal

    - name: Build web project
      run: dotnet build ${{ env.webProject }} --configuration ${{ env.buildConfiguration }} --no-restore /p:Version=${{ env.GitVersion.SemVer }} /p:PublicRelease=true /p:RunAnalyzersDuringBuild=true

    - name: Build test project
      run: dotnet build ${{ env.testProjects }} --configuration ${{ env.buildConfiguration }} --no-restore /p:Version=${{ env.GitVersion.SemVer }} /p:PublicRelease=true /p:RunAnalyzersDuringBuild=true

    - name: Test
      run: dotnet test ${{ env.testProjects }} --configuration ${{ env.buildConfiguration }} --no-restore --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
      env:
        TRX_FILE_NAME: 'Market.Comparison.Auth Test Run from build pipeline'